import { createFailedScore, createShuffledCopy, createSuccessfulScore, wasSubmittedAfterDeadline } from "./shared.ts";
import type { ChallengeDefinition, ChoiceChallengeAnswer, ChoiceChallengeGradingKey } from "../types.ts";

const RANDOMNESS_AUDIT_LABELS = ["A", "B", "C", "D"];

export const randomnessAuditChallenge: ChallengeDefinition = {
	type: "randomness_audit",
	async start() {
		const shuffledChoices = getShuffledRandomnessAuditChoices();
		const expectedLabel = shuffledChoices.find((choice) => choice.isPrng)?.label ?? "A";

		return {
			promptPayload: {
				kind: "multiple_choice",
				answerFormat: "choice_id",
				instruction: "Pick the PRNG string.",
				body: "One string below was generated by a PRNG. The other three were made to look random by a human.",
				layout: "grid",
				choices: shuffledChoices.map((choice) => ({
					id: choice.label,
					label: choice.label,
					description: choice.bits,
				})),
			},
			gradingKey: {
				answerFormat: "choice_id",
				expectedChoiceId: expectedLabel,
			},
			timeLimitMs: 5000,
		};
	},
	async score(context) {
		if (wasSubmittedAfterDeadline(context)) {
			return createFailedScore("deadline_exceeded");
		}

		const submittedLabel = String((context.answer as ChoiceChallengeAnswer | undefined)?.choiceId ?? "");
		const expectedLabel = (context.gradingKey as ChoiceChallengeGradingKey).expectedChoiceId;

		if (submittedLabel === expectedLabel) {
			return createSuccessfulScore();
		}

		return createFailedScore("incorrect_answer");
	},
};

function getShuffledRandomnessAuditChoices(): Array<{ label: string; bits: string; isPrng: boolean }> {
	const uniqueBitChoices = createUniqueBitChoices();
	const labeledChoices = uniqueBitChoices.map((choice, index) => ({
		label: RANDOMNESS_AUDIT_LABELS[index],
		bits: choice.bits,
		isPrng: choice.isPrng,
	}));

	return createShuffledCopy(labeledChoices);
}

function createUniqueBitChoices(): Array<{ bits: string; isPrng: boolean }> {
	const seenBits = new Set<string>();
	const choices: Array<{ bits: string; isPrng: boolean }> = [];

	while (choices.length < 3) {
		const bits = createHumanLikeBits(96);
		if (seenBits.has(bits)) {
			continue;
		}

		seenBits.add(bits);
		choices.push({ bits, isPrng: false });
	}

	while (choices.length < 4) {
		const bits = createPrngBits(96);
		if (seenBits.has(bits)) {
			continue;
		}

		seenBits.add(bits);
		choices.push({ bits, isPrng: true });
	}

	return choices;
}

function createPrngBits(length: number): string {
	const bytes = new Uint8Array(length);
	crypto.getRandomValues(bytes);
	return Array.from(bytes, (value) => (value % 2 === 0 ? "0" : "1")).join("");
}

function createHumanLikeBits(length: number): string {
	let result = "";
	let zeroCount = 0;
	let oneCount = 0;

	while (result.length < length) {
		const previousCharacter = result.at(-1) ?? "";
		const trailingRunLength = countTrailingCharacters(result, previousCharacter);
		const biasedChoice = Math.random() < 0.5 ? "0" : "1";

		let nextCharacter = biasedChoice;

		if (trailingRunLength >= 2 && previousCharacter) {
			nextCharacter = previousCharacter === "0" ? "1" : "0";
		}

		if (zeroCount > oneCount + 2) {
			nextCharacter = "1";
		}

		if (oneCount > zeroCount + 2) {
			nextCharacter = "0";
		}

		if (nextCharacter === "0") {
			zeroCount += 1;
		} else {
			oneCount += 1;
		}

		result += nextCharacter;
	}

	return result;
}

function countTrailingCharacters(value: string, targetCharacter: string): number {
	let count = 0;

	for (let index = value.length - 1; index >= 0; index -= 1) {
		if (value[index] !== targetCharacter) {
			break;
		}

		count += 1;
	}

	return count;
}
