import { createBarb, createFailedScore, createShuffledCopy, createSuccessfulScore, wasSubmittedAfterDeadline } from "./shared.ts";
import type {
	ChallengeDefinition,
	ChallengeStartContext,
	ChoiceChallengeAnswer,
	ChoiceChallengeGradingKey,
	MultipleChoiceChallengePrompt,
} from "../types.ts";

const RANDOMNESS_AUDIT_LABELS = ["A", "B", "C", "D"];
const RANDOMNESS_AUDIT_TIME_LIMIT_MS = 5000;

export const randomnessAuditChallenge = {
	type: "randomness_audit",
	catalog: {
		responseFormat: {
			description: "Submit answer.choiceId with the id of the chosen prompt choice.",
			answer: { choiceId: "<choice-id>" },
		},
		example: {
			prompt: {
				kind: "multiple_choice",
				answerFormat: "choice_id",
				instruction: "Pick the PRNG string.",
				body: "One string below was generated by a PRNG. The other three were made to look random by a human.",
				layout: "grid",
				choices: [
					{ id: "A", label: "A", description: "0101010110101010" },
					{ id: "B", label: "B", description: "0011011010010110" },
					{ id: "C", label: "C", description: "1110100001010011" },
					{ id: "D", label: "D", description: "1010101011010101" },
				],
			},
			answer: { choiceId: "C" },
		},
		timeLimitMs: RANDOMNESS_AUDIT_TIME_LIMIT_MS,
	},
	async start(_context: ChallengeStartContext) {
		const shuffledChoices = getShuffledRandomnessAuditChoices();
		const expectedLabel = shuffledChoices.find((choice) => choice.isPrng)?.label ?? "A";

		return {
			promptPayload: {
				kind: "multiple_choice",
				answerFormat: "choice_id",
				instruction: "Pick the PRNG string.",
				body: "One string below was generated by a PRNG. The other three were made to look random by a human.",
				layout: "grid",
				choices: shuffledChoices.map((choice) => ({
					id: choice.label,
					label: choice.label,
					description: choice.bits,
				})),
			},
			gradingKey: {
				answerFormat: "choice_id",
				expectedChoiceId: expectedLabel,
			},
			timeLimitMs: RANDOMNESS_AUDIT_TIME_LIMIT_MS,
		};
	},
	async score(context) {
		if (wasSubmittedAfterDeadline(context)) {
			return {
				...createFailedScore("deadline_exceeded"),
				barb: createBarb("Randomness expired before your intuition booted"),
			};
		}

		const submittedLabel = String((context.answer as ChoiceChallengeAnswer | undefined)?.choiceId ?? "");
		const expectedLabel = (context.gradingKey as ChoiceChallengeGradingKey).expectedChoiceId;

		if (submittedLabel === expectedLabel) {
			return createSuccessfulScore();
		}

		return {
			...createFailedScore("incorrect_answer"),
			barb: createRandomnessAuditBarb(context.promptPayload, submittedLabel, expectedLabel),
			barbContext: {
				challengeType: "randomness_audit",
				expectedChoiceId: expectedLabel,
				submittedChoiceId: submittedLabel,
			},
		};
	},
} satisfies ChallengeDefinition<
	"randomness_audit",
	MultipleChoiceChallengePrompt,
	ChoiceChallengeGradingKey,
	ChoiceChallengeAnswer
>;

function getShuffledRandomnessAuditChoices(): Array<{ label: string; bits: string; isPrng: boolean }> {
	const uniqueBitChoices = createUniqueBitChoices();
	const labeledChoices = uniqueBitChoices.map((choice, index) => ({
		label: RANDOMNESS_AUDIT_LABELS[index],
		bits: choice.bits,
		isPrng: choice.isPrng,
	}));

	return createShuffledCopy(labeledChoices);
}

function createUniqueBitChoices(): Array<{ bits: string; isPrng: boolean }> {
	const seenBits = new Set<string>();
	const choices: Array<{ bits: string; isPrng: boolean }> = [];

	while (choices.length < 3) {
		const bits = createHumanLikeBits(96);
		if (seenBits.has(bits)) {
			continue;
		}

		seenBits.add(bits);
		choices.push({ bits, isPrng: false });
	}

	while (choices.length < 4) {
		const bits = createPrngBits(96);
		if (seenBits.has(bits)) {
			continue;
		}

		seenBits.add(bits);
		choices.push({ bits, isPrng: true });
	}

	return choices;
}

function createPrngBits(length: number): string {
	const bytes = new Uint8Array(length);
	crypto.getRandomValues(bytes);
	return Array.from(bytes, (value) => (value % 2 === 0 ? "0" : "1")).join("");
}

function createHumanLikeBits(length: number): string {
	let result = "";
	let zeroCount = 0;
	let oneCount = 0;

	while (result.length < length) {
		const previousCharacter = result.at(-1) ?? "";
		const trailingRunLength = countTrailingCharacters(result, previousCharacter);
		const biasedChoice = Math.random() < 0.5 ? "0" : "1";

		let nextCharacter = biasedChoice;

		if (trailingRunLength >= 2 && previousCharacter) {
			nextCharacter = previousCharacter === "0" ? "1" : "0";
		}

		if (zeroCount > oneCount + 2) {
			nextCharacter = "1";
		}

		if (oneCount > zeroCount + 2) {
			nextCharacter = "0";
		}

		if (nextCharacter === "0") {
			zeroCount += 1;
		} else {
			oneCount += 1;
		}

		result += nextCharacter;
	}

	return result;
}

function createRandomnessAuditBarb(
	prompt: MultipleChoiceChallengePrompt,
	submittedLabel: string,
	expectedLabel: string,
): string {
	const submittedChoice = prompt.choices.find((choice) => choice.id === submittedLabel);
	if (submittedChoice && submittedChoice.id !== expectedLabel && isHumanPattern(submittedChoice.description ?? "")) {
		return createBarb("That pattern has fingerprints all over it");
	}

	return createBarb("You selected the human-looking entropy. Familiar, perhaps");
}

function isHumanPattern(bits: string): boolean {
	return /([01])\1{2,}/.test(bits) || /(0101|1010)/.test(bits);
}

function countTrailingCharacters(value: string, targetCharacter: string): number {
	let count = 0;

	for (let index = value.length - 1; index >= 0; index -= 1) {
		if (value[index] !== targetCharacter) {
			break;
		}

		count += 1;
	}

	return count;
}
