import test from "node:test";
import assert from "node:assert/strict";

import { randomnessAuditChallenge } from "./_randomness-audit.ts";
import type { ChoiceChallengeGradingKey, MultipleChoiceChallengePrompt } from "../types.ts";

test("randomness audit returns challenge barbs for wrong and late answers", async () => {
	const promptPayload: MultipleChoiceChallengePrompt = {
		kind: "multiple_choice",
		answerFormat: "choice_id",
		instruction: "Pick the PRNG string.",
		body: "One string below was generated by a PRNG. The other three were made to look random by a human.",
		layout: "grid",
		choices: [
			{ id: "A", label: "A", description: "0101010101010101" },
			{ id: "B", label: "B", description: "0011011010010110" },
		],
	};
	const gradingKey: ChoiceChallengeGradingKey = {
		answerFormat: "choice_id",
		expectedChoiceId: "B",
	};
	const baseContext = {
		promptPayload,
		gradingKey,
		submittedAt: new Date("2026-06-24T12:00:05.000Z"),
		deadlineAt: new Date("2026-06-24T12:00:20.000Z"),
	};

	const patternedWrongResult = await randomnessAuditChallenge.score({
		...baseContext,
		answer: { choiceId: "A" },
	});
	assert.equal(patternedWrongResult.score, 0);
	assert.equal(patternedWrongResult.verdict, "failed");
	assert.equal(patternedWrongResult.reason, "incorrect_answer");
	assert.match(patternedWrongResult.barb ?? "", /^That pattern has fingerprints all over it, .+\.$/);
	assert.deepEqual(patternedWrongResult.barbContext, {
		challengeType: "randomness_audit",
		expectedChoiceId: "B",
		submittedChoiceId: "A",
	});

	const invalidWrongResult = await randomnessAuditChallenge.score({
		...baseContext,
		answer: { choiceId: "Z" },
	});
	assert.match(invalidWrongResult.barb ?? "", /^You selected the human-looking entropy\. Familiar, perhaps, .+\.$/);

	const lateResult = await randomnessAuditChallenge.score({
		...baseContext,
		answer: { choiceId: "B" },
		submittedAt: new Date("2026-06-24T12:00:21.000Z"),
	});
	assert.equal(lateResult.score, 0);
	assert.equal(lateResult.verdict, "failed");
	assert.equal(lateResult.reason, "deadline_exceeded");
	assert.match(lateResult.barb ?? "", /^Randomness expired before your intuition booted, .+\.$/);
});
