interface Env {
	SITES: KVNamespace;
	SESSIONS: KVNamespace;
	ASSETS: Fetcher;
	SIGNING_SECRET: string;
	DEFAULT_SITE_CONFIG?: string;
	DEV_SIGNING_SECRET?: string;
}

type Verdict = "robot" | "human" | "failed";
type SessionStatus = "issued" | "completed" | "expired";
type ChallengeType = "timed_math" | "randomness_audit" | "code_error";

interface SiteConfig {
	siteKey: string;
	secret: string;
	allowedHostnames: string[];
}

interface ChallengeSession {
	id: string;
	siteKey: string;
	hostname: string;
	mode: "prove_robot";
	challengeType: ChallengeType;
	issuedAt: string;
	deadlineAt: string;
	completedAt: string | null;
	status: SessionStatus;
	promptPayload: unknown;
	gradingKey: unknown;
	score: number | null;
	verdict: Verdict | null;
	resultTokenId: string | null;
}

interface ChallengeStartContext {
	siteKey: string;
	hostname: string;
	now: Date;
}

interface ChallengeStartResult {
	promptPayload: unknown;
	gradingKey: unknown;
	timeLimitMs: number;
}

interface ChallengeScoreContext {
	promptPayload: unknown;
	gradingKey: unknown;
	answer: unknown;
	submittedAt: Date;
	deadlineAt: Date;
}

interface ChallengeScoreResult {
	score: number;
	verdict: Verdict;
	reason?: string;
}

interface ChallengeDefinition {
	type: ChallengeType;
	start(ctx: ChallengeStartContext): Promise<ChallengeStartResult>;
	score(ctx: ChallengeScoreContext): Promise<ChallengeScoreResult>;
}

interface StartRequestBody {
	siteKey?: string;
	hostname?: string;
	mode?: string;
}

interface SubmitRequestBody {
	sessionId?: string;
	answer?: unknown;
}

interface VerifyRequestBody {
	secret?: string;
	resultToken?: string;
}

interface ResultTokenPayload {
	tid: string;
	sid: string;
	sk: string;
	host: string;
	ctype: ChallengeType;
	verdict: Verdict;
	score: number;
	iat: number;
	exp: number;
}

const SESSION_TTL_SECONDS = 60 * 15;
const RESULT_TOKEN_TTL_SECONDS = 60 * 5;
const APP_BASE_PATH = "/im-a-robot";
const API_PATH_PREFIX = `${APP_BASE_PATH}/api`;

const corsHeaders = {
	"Access-Control-Allow-Origin": "*",
	"Access-Control-Allow-Methods": "POST, OPTIONS",
	"Access-Control-Allow-Headers": "Content-Type",
	"Access-Control-Max-Age": "86400",
};

const challenges: ChallengeDefinition[] = [
	{
		type: "timed_math",
		async start() {
			const a = randomInt(120, 999);
			const b = randomInt(20, 99);
			const c = randomInt(11, 89);

			return {
				promptPayload: {
					question: `What is ${a} * ${b} + ${c}?`,
					answerFormat: "integer",
				},
				gradingKey: {
					expected: a * b + c,
				},
				timeLimitMs: 5000,
			};
		},
		async score(ctx) {
			if (ctx.submittedAt > ctx.deadlineAt) {
				return fail("deadline_exceeded");
			}

			const answer = Number((ctx.answer as { value?: string })?.value);
			const expected = (ctx.gradingKey as { expected: number }).expected;

			if (Number.isFinite(answer) && answer === expected) {
				return pass();
			}

			return fail("incorrect_answer");
		},
	},
	{
		type: "randomness_audit",
		async start() {
			const uniqueStrings = makeUniqueBitChoices();
			const labels = ["A", "B", "C", "D"];
			const choices = uniqueStrings.map((choice, index) => ({
				label: labels[index],
				bits: choice.bits,
				isPrng: choice.isPrng,
			}));
			shuffleInPlace(choices);

			const correctLabel = choices.find((choice) => choice.isPrng)?.label ?? "A";

			return {
				promptPayload: {
					description: "One string below was generated by a PRNG. The other three were made to look random by a human. Pick the PRNG string.",
					choices: choices.map((choice) => ({
						label: choice.label,
						bits: choice.bits,
					})),
				},
				gradingKey: {
					expectedLabel: correctLabel,
				},
				timeLimitMs: 5000,
			};
		},
		async score(ctx) {
			if (ctx.submittedAt > ctx.deadlineAt) {
				return fail("deadline_exceeded");
			}

			const label = String((ctx.answer as { value?: string })?.value ?? "");
			const expectedLabel = (ctx.gradingKey as { expectedLabel: string }).expectedLabel;

			if (label === expectedLabel) {
				return pass();
			}

			return fail("incorrect_answer");
		},
	},
	{
		type: "code_error",
		async start() {
			const choices = [
				{ value: "mutates_input", label: "It mutates the input array in place." },
				{ value: "off_by_one", label: "The loop runs one element too far and reads past the end." },
				{ value: "wrong_divisor", label: "It divides by the sum instead of the length." },
				{ value: "const_sum", label: "The sum variable should be a const." },
			];
			shuffleInPlace(choices);

			return {
				promptPayload: {
					description: "Find the bug in the snippet. Pick the best answer.",
					code: `function average(values) {
  let sum = 0;

  for (let i = 0; i <= values.length; i++) {
    sum += values[i];
  }

  return sum / values.length;
}`,
					choices,
				},
				gradingKey: {
					expectedChoice: "off_by_one",
				},
				timeLimitMs: 7000,
			};
		},
		async score(ctx) {
			if (ctx.submittedAt > ctx.deadlineAt) {
				return fail("deadline_exceeded");
			}

			const value = String((ctx.answer as { value?: string })?.value ?? "");
			const expectedChoice = (ctx.gradingKey as { expectedChoice: string }).expectedChoice;

			if (value === expectedChoice) {
				return pass();
			}

			return fail("incorrect_answer");
		},
	},
];

export default {
	async fetch(request: Request, env: Env): Promise<Response> {
		const url = new URL(request.url);
		const pathname = normalizePathname(url.pathname);

		if (request.method === "OPTIONS") {
			return new Response(null, { headers: corsHeaders });
		}

		try {
			if (request.method === "POST" && isApiPath(pathname, "/api/challenge/start")) {
				return await handleChallengeStart(request, env);
			}

			if (request.method === "POST" && isApiPath(pathname, "/api/challenge/submit")) {
				return await handleChallengeSubmit(request, env);
			}

			if (request.method === "POST" && isApiPath(pathname, "/api/verify")) {
				return await handleVerify(request, env);
			}

			if (request.method === "GET" && isHealthPath(pathname)) {
				return jsonResponse({ ok: true }, 200);
			}

			if (request.method === "GET" || request.method === "HEAD") {
				return await serveStaticAsset(request, env, pathname);
			}

			return jsonError("not_found", 404);
		} catch (error) {
			console.error(error);
			return jsonError("internal_error", 500);
		}
	},
};

async function handleChallengeStart(request: Request, env: Env): Promise<Response> {
	const body = (await request.json()) as StartRequestBody;
	const siteKey = body.siteKey?.trim();
	const mode = body.mode?.trim() ?? "prove_robot";
	const requestUrl = new URL(request.url);
	const hostname = normalizeHostname(body.hostname, request.headers.get("Origin"), requestUrl.host);

	if (!siteKey) {
		return jsonError("invalid_site_key", 400);
	}

	if (mode !== "prove_robot") {
		return jsonError("invalid_mode", 400);
	}

	if (!hostname) {
		return jsonError("invalid_hostname", 400);
	}

	const site = await loadSiteConfig(env, siteKey);
	if (!site) {
		return jsonError("invalid_site_key", 404);
	}

	if (!site.allowedHostnames.includes(hostname)) {
		return jsonError("hostname_not_allowed", 403);
	}

	const challenge = pickRandomChallenge();
	const now = new Date();
	const startResult = await challenge.start({ siteKey, hostname, now });
	const issuedAt = now.toISOString();
	const deadlineAt = new Date(now.getTime() + startResult.timeLimitMs).toISOString();
	const sessionId = randomId("sess");

	const session: ChallengeSession = {
		id: sessionId,
		siteKey,
		hostname,
		mode: "prove_robot",
		challengeType: challenge.type,
		issuedAt,
		deadlineAt,
		completedAt: null,
		status: "issued",
		promptPayload: startResult.promptPayload,
		gradingKey: startResult.gradingKey,
		score: null,
		verdict: null,
		resultTokenId: null,
	};

	await env.SESSIONS.put(`session:${sessionId}`, JSON.stringify(session), {
		expirationTtl: SESSION_TTL_SECONDS,
	});

	return jsonResponse({
		sessionId,
		challenge: {
			type: challenge.type,
			prompt: startResult.promptPayload,
		},
		issuedAt,
		deadlineAt,
	});
}

async function handleChallengeSubmit(request: Request, env: Env): Promise<Response> {
	const body = (await request.json()) as SubmitRequestBody;
	const sessionId = body.sessionId?.trim();
	const signingSecret = getSigningSecret(env);

	if (!sessionId) {
		return jsonError("session_not_found", 400);
	}

	if (!signingSecret) {
		return jsonError("missing_signing_secret", 500);
	}

	const session = await loadSession(env, sessionId);
	if (!session) {
		return jsonError("session_not_found", 404);
	}

	if (session.status === "completed") {
		return jsonError("session_already_completed", 409);
	}

	const submittedAt = new Date();
	const deadlineAt = new Date(session.deadlineAt);
	const challenge = getChallengeByType(session.challengeType);

	const result = await challenge.score({
		promptPayload: session.promptPayload,
		gradingKey: session.gradingKey,
		answer: body.answer,
		submittedAt,
		deadlineAt,
	});

	const completedAt = submittedAt.toISOString();
	const tokenIssuedAt = Math.floor(submittedAt.getTime() / 1000);
	const tokenExpiresAt = tokenIssuedAt + RESULT_TOKEN_TTL_SECONDS;
	const tokenId = randomId("rtok");

	session.status = submittedAt > deadlineAt ? "expired" : "completed";
	session.completedAt = completedAt;
	session.score = result.score;
	session.verdict = result.verdict;
	session.resultTokenId = tokenId;

	await env.SESSIONS.put(`session:${session.id}`, JSON.stringify(session), {
		expirationTtl: SESSION_TTL_SECONDS,
	});

	if (result.verdict === "failed") {
		return jsonResponse(
			{
				success: false,
				verdict: "failed",
				reason: result.reason ?? "incorrect_answer",
				completedAt,
			},
			200,
		);
	}

	const resultToken = await signResultToken(
		{
			tid: tokenId,
			sid: session.id,
			sk: session.siteKey,
			host: session.hostname,
			ctype: session.challengeType,
			verdict: result.verdict,
			score: result.score,
			iat: tokenIssuedAt,
			exp: tokenExpiresAt,
		},
		signingSecret,
	);

	return jsonResponse({
		success: true,
		verdict: result.verdict,
		score: result.score,
		resultToken,
		completedAt,
		expiresAt: new Date(tokenExpiresAt * 1000).toISOString(),
	});
}

async function handleVerify(request: Request, env: Env): Promise<Response> {
	const body = (await request.json()) as VerifyRequestBody;
	const secret = body.secret?.trim();
	const resultToken = body.resultToken?.trim();
	const signingSecret = getSigningSecret(env);

	if (!secret) {
		return jsonError("invalid_secret", 400);
	}

	if (!resultToken) {
		return jsonError("invalid_result_token", 400);
	}

	if (!signingSecret) {
		return jsonError("missing_signing_secret", 500);
	}

	const payload = await verifyResultToken(resultToken, signingSecret);
	if (!payload) {
		return jsonError("invalid_result_token", 401);
	}

	const site = await loadSiteConfig(env, payload.sk);
	if (!site || site.secret !== secret) {
		return jsonError("invalid_secret", 401);
	}

	const session = await loadSession(env, payload.sid);
	if (!session) {
		return jsonError("session_not_found", 404);
	}

	if (session.resultTokenId !== payload.tid) {
		return jsonError("invalid_result_token", 401);
	}

	return jsonResponse({
		success: true,
		verdict: payload.verdict,
		challengeType: payload.ctype,
		score: payload.score,
		hostname: payload.host,
		issuedAt: session.issuedAt,
		completedAt: session.completedAt,
	});
}

async function loadSiteConfig(env: Env, siteKey: string): Promise<SiteConfig | null> {
	const siteFromKv = await env.SITES.get(`site:${siteKey}`, "json");
	if (siteFromKv) {
		return siteFromKv as SiteConfig;
	}

	const fallback = parseDefaultSite(env.DEFAULT_SITE_CONFIG);
	if (fallback?.siteKey === siteKey) {
		return fallback;
	}

	return null;
}

function getSigningSecret(env: Env): string | null {
	const secret = env.SIGNING_SECRET?.trim() || env.DEV_SIGNING_SECRET?.trim();
	return secret || null;
}

function parseDefaultSite(raw?: string): SiteConfig | null {
	if (!raw) {
		return null;
	}

	try {
		const parsed = JSON.parse(raw) as SiteConfig;
		if (parsed.siteKey && parsed.secret && Array.isArray(parsed.allowedHostnames)) {
			return parsed;
		}
	} catch (error) {
		console.error("Failed to parse DEFAULT_SITE_CONFIG", error);
	}

	return null;
}

async function loadSession(env: Env, sessionId: string): Promise<ChallengeSession | null> {
	const session = await env.SESSIONS.get(`session:${sessionId}`, "json");
	return (session as ChallengeSession | null) ?? null;
}

function pickRandomChallenge(): ChallengeDefinition {
	return challenges[randomInt(0, challenges.length - 1)];
}

function getChallengeByType(type: ChallengeType): ChallengeDefinition {
	const challenge = challenges.find((candidate) => candidate.type === type);
	if (!challenge) {
		throw new Error(`Unknown challenge type: ${type}`);
	}
	return challenge;
}

function pass(): ChallengeScoreResult {
	return { score: 1, verdict: "robot" };
}

function fail(reason: string): ChallengeScoreResult {
	return { score: 0, verdict: "failed", reason };
}

function normalizeHostname(hostname?: string, origin?: string | null, fallbackHost?: string | null): string | null {
	if (hostname) {
		return safeHostname(hostname);
	}

	if (origin) {
		try {
			return new URL(origin).host;
		} catch {
			return null;
		}
	}

	return fallbackHost ?? null;
}

async function serveStaticAsset(request: Request, env: Env, pathname: string): Promise<Response> {
	const assetPath = toAssetPath(pathname);
	if (!assetPath) {
		return jsonError("not_found", 404);
	}

	const requestUrl = new URL(request.url);
	const assetUrl = new URL(assetPath, requestUrl.origin);
	const assetRequest = new Request(assetUrl.toString(), request);
	return env.ASSETS.fetch(assetRequest);
}

function normalizePathname(pathname: string): string {
	if (pathname.length > 1 && pathname.endsWith("/")) {
		return pathname.slice(0, -1);
	}
	return pathname || "/";
}

function isApiPath(pathname: string, suffix: string): boolean {
	return pathname === suffix || pathname === `${API_PATH_PREFIX}${suffix.slice(4)}`;
}

function isHealthPath(pathname: string): boolean {
	return pathname === "/health" || pathname === `${APP_BASE_PATH}/health`;
}

function toAssetPath(pathname: string): string | null {
	if (pathname === APP_BASE_PATH || pathname === `${APP_BASE_PATH}/`) {
		return "/index.html";
	}

	if (pathname === `${APP_BASE_PATH}/debug` || pathname === `${APP_BASE_PATH}/debug/`) {
		return "/debug/index.html";
	}

	if (pathname === `${APP_BASE_PATH}/privacy` || pathname === `${APP_BASE_PATH}/privacy/`) {
		return "/privacy/index.html";
	}

	if (pathname === `${APP_BASE_PATH}/terms` || pathname === `${APP_BASE_PATH}/terms/`) {
		return "/terms/index.html";
	}

	if (pathname.startsWith(`${APP_BASE_PATH}/`)) {
		return pathname.slice(APP_BASE_PATH.length);
	}

	if (pathname === "/" || pathname === "/index.html") {
		return "/index.html";
	}

	if (pathname.startsWith("/")) {
		return pathname;
	}

	return null;
}

function safeHostname(value: string): string | null {
	try {
		if (value.includes("://")) {
			return new URL(value).host;
		}
		return new URL(`https://${value}`).host;
	} catch {
		return null;
	}
}

function jsonResponse(body: unknown, status = 200): Response {
	return new Response(JSON.stringify(body, null, 2), {
		status,
		headers: {
			"Content-Type": "application/json; charset=utf-8",
			...corsHeaders,
		},
	});
}

function jsonError(code: string, status: number): Response {
	return jsonResponse({ success: false, error: code }, status);
}

function randomInt(min: number, max: number): number {
	return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randomId(prefix: string): string {
	const bytes = new Uint8Array(12);
	crypto.getRandomValues(bytes);
	return `${prefix}_${bytesToHex(bytes)}`;
}

function bytesToHex(bytes: Uint8Array): string {
	return Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join("");
}

function makePrngBits(length: number): string {
	const bytes = new Uint8Array(length);
	crypto.getRandomValues(bytes);
	return Array.from(bytes, (value) => (value % 2 === 0 ? "0" : "1")).join("");
}

function makeHumanLikeBits(length: number): string {
	let result = "";
	let zeros = 0;
	let ones = 0;

	while (result.length < length) {
		const previous = result.at(-1);
		const runLength = countTrailingRun(result, previous ?? "");
		const biasedChoice = Math.random() < 0.5 ? "0" : "1";

		let next = biasedChoice;

		if (runLength >= 2 && previous) {
			next = previous === "0" ? "1" : "0";
		}

		if (zeros > ones + 2) {
			next = "1";
		}

		if (ones > zeros + 2) {
			next = "0";
		}

		if (next === "0") {
			zeros += 1;
		} else {
			ones += 1;
		}

		result += next;
	}

	return result;
}

function makeUniqueBitChoices(): Array<{ bits: string; isPrng: boolean }> {
	const seen = new Set<string>();
	const choices: Array<{ bits: string; isPrng: boolean }> = [];

	while (choices.length < 3) {
		const bits = makeHumanLikeBits(96);
		if (seen.has(bits)) {
			continue;
		}
		seen.add(bits);
		choices.push({ bits, isPrng: false });
	}

	while (choices.length < 4) {
		const bits = makePrngBits(96);
		if (seen.has(bits)) {
			continue;
		}
		seen.add(bits);
		choices.push({ bits, isPrng: true });
	}

	return choices;
}

function countTrailingRun(value: string, target: string): number {
	let count = 0;
	for (let index = value.length - 1; index >= 0; index -= 1) {
		if (value[index] !== target) {
			break;
		}
		count += 1;
	}
	return count;
}

function shuffleInPlace<T>(array: T[]): void {
	for (let index = array.length - 1; index > 0; index -= 1) {
		const swapIndex = randomInt(0, index);
		const current = array[index];
		array[index] = array[swapIndex];
		array[swapIndex] = current;
	}
}

function shuffleCopy<T>(array: T[]): T[] {
	const copy = [...array];
	shuffleInPlace(copy);
	return copy;
}

async function signResultToken(payload: ResultTokenPayload, secret: string): Promise<string> {
	const header = { alg: "HS256", typ: "RBT" };
	const encodedHeader = encodeBase64Url(JSON.stringify(header));
	const encodedPayload = encodeBase64Url(JSON.stringify(payload));
	const unsigned = `${encodedHeader}.${encodedPayload}`;
	const signature = await hmacSign(unsigned, secret);
	return `${unsigned}.${signature}`;
}

async function verifyResultToken(token: string, secret: string): Promise<ResultTokenPayload | null> {
	const parts = token.split(".");
	if (parts.length !== 3) {
		return null;
	}

	const [encodedHeader, encodedPayload, signature] = parts;
	const unsigned = `${encodedHeader}.${encodedPayload}`;
	const expectedSignature = await hmacSign(unsigned, secret);

	if (!timingSafeEqual(signature, expectedSignature)) {
		return null;
	}

	try {
		const payload = JSON.parse(decodeBase64Url(encodedPayload)) as ResultTokenPayload;
		const now = Math.floor(Date.now() / 1000);
		if (payload.exp < now) {
			return null;
		}
		return payload;
	} catch {
		return null;
	}
}

async function hmacSign(value: string, secret: string): Promise<string> {
	const key = await crypto.subtle.importKey(
		"raw",
		new TextEncoder().encode(secret),
		{
			name: "HMAC",
			hash: "SHA-256",
		},
		false,
		["sign"],
	);
	const signature = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(value));
	return encodeBytesBase64Url(new Uint8Array(signature));
}

function encodeBase64Url(value: string): string {
	return encodeBytesBase64Url(new TextEncoder().encode(value));
}

function encodeBytesBase64Url(bytes: Uint8Array): string {
	let binary = "";
	for (const byte of bytes) {
		binary += String.fromCharCode(byte);
	}
	return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}

function decodeBase64Url(value: string): string {
	const normalized = value.replace(/-/g, "+").replace(/_/g, "/");
	const padded = normalized.padEnd(normalized.length + ((4 - (normalized.length % 4)) % 4), "=");
	return atob(padded);
}

function timingSafeEqual(left: string, right: string): boolean {
	if (left.length !== right.length) {
		return false;
	}

	let diff = 0;
	for (let index = 0; index < left.length; index += 1) {
		diff |= left.charCodeAt(index) ^ right.charCodeAt(index);
	}
	return diff === 0;
}
